name: frontend
type: "php:8.2"

hooks:
    build: |
        npm install
        npx node-sass public/scss/ -o public/css/ --output-style compressed --recursive


web:
    locations:
        "/":
            root: "public"
            index: ["index.html"]
            allow: true

