name: frontend
type: "php:8.2"
web:
    locations:
        "/":
            root: "public"
            index: [ "index.html" ]
            # Füge das dazu:
            try_files: [ "$uri", "/index.html" ]
        # Beispiel für API:
        "/api":
            passthru: true


