name: frontend
type: "php:8.2"
web:
    locations:
        "/":
            root: "public"
            index: ["index.html"]
            allow: true
            # Das ist der Schlüssel!
            fallback: "index.html"
        "/api":
            passthru: true


