name: frontend
type: "php:8.2"

hooks:
  build:
    npx node-sass public/scss/ -o public/css/ --output-style compressed --recursive

web:
    locations:
        "/":
            root: "public"
            index: ["index.php", "index.html"]
            passthru: "/index.php"
            allow: true

