name: backend
type: "php:8.2"

web:
    locations:
        "/":
            root: "public"
            passthru: "/index.php"
            index:
                - index.php
            scripts: true
            expires: -1


mounts:
    "/var/uploads": "shared:files"

relationships:
    database: "db:postgresql"
    mongo: "mongodb:mongodb"

variables:
    env:
        APP_ENV: "prod"
        # Andere Symfony ENV falls nötig

crons:
    symfony-cron:
        spec: "0 * * * *"
        cmd: "php bin/console app:your:cron"
