name: backend
type: "php:8.2"
disk: 2048

web:
    locations:
        "/":
            root: "public"
            allow: true

mounts:
    "/var/uploads": "shared:files"

relationships:
    database: "db:postgresql"
    mongo: "mongodb:mongodb"

variables:
    env:
        APP_ENV: "prod"
        # Andere Symfony ENV falls nötig

crons:
    symfony-cron:
        spec: "0 * * * *"
        cmd: "php bin/console app:your:cron"
