name: backend
type: "php:8.2"
disk: 2048

runtime:
    extensions:
        - mongodb

web:
    locations:
        "/":
            root: "public"
            passthru: "/index.php"
            index:
                - index.php
            scripts: true
            expires: -1


mounts:
    "/var/uploads": "shared:files"

relationships:
    database: "db:postgresql"
    mongo: "mongodb:mongodb"

variables:
    env:
        APP_ENV: "prod"
        MONGODB_DATABASE: "arcadiazoo_mongo_db"
        MONGODB_URL: "mongodb://Bajram:Vfbstuttgart@arcadiazoo-mongodb:27017/arcadiazoo_mongo_db?authSource=admin"
        DATABASE_URL: "postgresql://bajram:Vfbstuttgart@127.0.0.1:5432/arcadiaZoo?serverVersion=16&charset=utf8"

crons:
    symfony-cron:
        spec: "0 * * * *"
        cmd: "php bin/console app:your:cron"
