name: backend
type: 'php:8.2'
build:
    flavor: composer

dependencies:
    php:
        mongodb: "*"

relationships:
    dbpostgres: "dbpostgres:postgresql"
    dbmongo: "dbmongo:mongodb"

web:
    locations:
        "/":
            root: "public"
            passthru: "/index.php"

mounts:
    "/var/uploads": "shared:files/uploads"

hooks:
    build: |
        composer install
    deploy: |
        php bin/console doctrine:migrations:migrate --no-interaction

crons:
    cron_command:
        spec: '0 3 * * *'
        cmd: 'php bin/console app:cron'

