services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arcadiazoo-php-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - mongodb
    networks:
      - arcadia_network


  db:
    image: postgres:17-alpine
    container_name: arcadiazoo-postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: bajram
      POSTGRES_PASSWORD: Vfbstuttgart
      POSTGRES_DB: arcadiaZoo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - arcadia_network

  mongodb:
    image: mongo:5.0
    container_name: arcadiazoo-mongodb
    restart: always
    networks:
      - arcadia_network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Bajram
      MONGO_INITDB_ROOT_PASSWORD: Vfbstuttgart
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: arcadiazoo-mongo-express
    restart: always
    networks:
      - arcadia_network
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: arcadiazoo-mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: Bajram
      ME_CONFIG_MONGODB_ADMINPASSWORD: Vfbstuttgart
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: yourpassword
    depends_on:
      - mongodb

volumes:
  postgres-data:
  mongodb-data:

networks:
  arcadia_network:
    driver: bridge

