<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXvxb5EP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXvxb5EP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXvxb5EP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXvxb5EP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXvxb5EP\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xvxb5EP',
    'container.build_id' => 'cc1e7664',
    'container.build_time' => 1751812477,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXvxb5EP');
