<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0MN1OqM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0MN1OqM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0MN1OqM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0MN1OqM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0MN1OqM\App_KernelDevDebugContainer([
    'container.build_hash' => '0MN1OqM',
    'container.build_id' => 'cd53ea85',
    'container.build_time' => 1752511860,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0MN1OqM');
