<?php

namespace ContainerGyWsBeL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_TV5Q6AService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored.TV_5Q6A' shared service.
     *
     * @return \App\Controller\MailerService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ContactController::replyContactRequest()": the $mailerService argument is type-hinted with the non-existent class or interface: "App\\Controller\\MailerService". Did you forget to add a use statement?');
    }
}
