<?php

namespace ContainerGyWsBeL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZDqHbwService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.zDq_Hbw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zDq_Hbw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ConsultationController::incrementConsultation' => ['privates', '.service_locator.F1jaNar.App\\Controller\\ConsultationController::incrementConsultation()', 'getConsultationControllerincrementConsultationService', true],
            'App\\Controller\\ConsultationController::getConsultations' => ['privates', '.service_locator.F1jaNar.App\\Controller\\ConsultationController::getConsultations()', 'getConsultationControllergetConsultationsService', true],
            'App\\Controller\\ContactController::sendContactMail' => ['privates', '.service_locator..V3RrT8.App\\Controller\\ContactController::sendContactMail()', 'getContactControllersendContactMailService', true],
            'App\\Controller\\ContactController::replyContactRequest' => ['privates', '.service_locator.fbS0cpj', 'get_ServiceLocator_FbS0cpjService', true],
            'App\\Controller\\LoginController::register' => ['privates', '.service_locator.OxGaOcy.App\\Controller\\LoginController::register()', 'getLoginControllerregisterService', true],
            'App\\Controller\\RegistrationController::createUser' => ['privates', '.service_locator.KaWKm0J.App\\Controller\\RegistrationController::createUser()', 'getRegistrationControllercreateUserService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\ConsultationController:incrementConsultation' => ['privates', '.service_locator.F1jaNar.App\\Controller\\ConsultationController::incrementConsultation()', 'getConsultationControllerincrementConsultationService', true],
            'App\\Controller\\ConsultationController:getConsultations' => ['privates', '.service_locator.F1jaNar.App\\Controller\\ConsultationController::getConsultations()', 'getConsultationControllergetConsultationsService', true],
            'App\\Controller\\ContactController:sendContactMail' => ['privates', '.service_locator..V3RrT8.App\\Controller\\ContactController::sendContactMail()', 'getContactControllersendContactMailService', true],
            'App\\Controller\\ContactController:replyContactRequest' => ['privates', '.service_locator.fbS0cpj', 'get_ServiceLocator_FbS0cpjService', true],
            'App\\Controller\\LoginController:register' => ['privates', '.service_locator.OxGaOcy.App\\Controller\\LoginController::register()', 'getLoginControllerregisterService', true],
            'App\\Controller\\RegistrationController:createUser' => ['privates', '.service_locator.KaWKm0J.App\\Controller\\RegistrationController::createUser()', 'getRegistrationControllercreateUserService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ConsultationController::incrementConsultation' => '?',
            'App\\Controller\\ConsultationController::getConsultations' => '?',
            'App\\Controller\\ContactController::sendContactMail' => '?',
            'App\\Controller\\ContactController::replyContactRequest' => '?',
            'App\\Controller\\LoginController::register' => '?',
            'App\\Controller\\RegistrationController::createUser' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ConsultationController:incrementConsultation' => '?',
            'App\\Controller\\ConsultationController:getConsultations' => '?',
            'App\\Controller\\ContactController:sendContactMail' => '?',
            'App\\Controller\\ContactController:replyContactRequest' => '?',
            'App\\Controller\\LoginController:register' => '?',
            'App\\Controller\\RegistrationController:createUser' => '?',
        ]);
    }
}
