<?php

namespace ContainerGyWsBeL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_Swagger_Processor_NullablePropertyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'nelmio_api_doc.swagger.processor.nullable_property' shared service.
     *
     * @return \Nelmio\ApiDocBundle\Processor\NullablePropertyProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nelmio'.\DIRECTORY_SEPARATOR.'api-doc-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Processor'.\DIRECTORY_SEPARATOR.'NullablePropertyProcessor.php';

        return $container->privates['nelmio_api_doc.swagger.processor.nullable_property'] = new \Nelmio\ApiDocBundle\Processor\NullablePropertyProcessor();
    }
}
