<?php

namespace ContainerDdEbTms;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6tH44cKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6tH44cK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6tH44cK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\AdminDashboardController::createUser' => ['privates', '.service_locator.OxGaOcy.App\\Controller\\AdminDashboardController::createUser()', 'getAdminDashboardControllercreateUserService', true],
            'App\\Controller\\AdminDashboardController::listUsers' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\AdminDashboardController::listUsers()', 'getAdminDashboardControllerlistUsersService', true],
            'App\\Controller\\AdminDashboardController::updateUser' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\AdminDashboardController::updateUser()', 'getAdminDashboardControllerupdateUserService', true],
            'App\\Controller\\AdminDashboardController::deleteUser' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\AdminDashboardController::deleteUser()', 'getAdminDashboardControllerdeleteUserService', true],
            'App\\Controller\\AvisController::createAvis' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\AvisController::createAvis()', 'getAvisControllercreateAvisService', true],
            'App\\Controller\\AvisController::getValidatedAvis' => ['privates', '.service_locator.0qdY07o.App\\Controller\\AvisController::getValidatedAvis()', 'getAvisControllergetValidatedAvisService', true],
            'App\\Controller\\AvisController::getPendingAvis' => ['privates', '.service_locator.0qdY07o.App\\Controller\\AvisController::getPendingAvis()', 'getAvisControllergetPendingAvisService', true],
            'App\\Controller\\AvisController::validateAvis' => ['privates', '.service_locator.4BBdIOf.App\\Controller\\AvisController::validateAvis()', 'getAvisControllervalidateAvisService', true],
            'App\\Controller\\AvisController::deleteAvis' => ['privates', '.service_locator.4BBdIOf.App\\Controller\\AvisController::deleteAvis()', 'getAvisControllerdeleteAvisService', true],
            'App\\Controller\\ConsultationController::incrementConsultation' => ['privates', '.service_locator.F1jaNar.App\\Controller\\ConsultationController::incrementConsultation()', 'getConsultationControllerincrementConsultationService', true],
            'App\\Controller\\ConsultationController::getConsultations' => ['privates', '.service_locator..sUqPH6.App\\Controller\\ConsultationController::getConsultations()', 'getConsultationControllergetConsultationsService', true],
            'App\\Controller\\ContactController::deleteContactRequest' => ['privates', '.service_locator.qIOAC1G.App\\Controller\\ContactController::deleteContactRequest()', 'getContactControllerdeleteContactRequestService', true],
            'App\\Controller\\ContactController::testEmail' => ['privates', '.service_locator.emggfWL.App\\Controller\\ContactController::testEmail()', 'getContactControllertestEmailService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\AdminDashboardController:createUser' => ['privates', '.service_locator.OxGaOcy.App\\Controller\\AdminDashboardController::createUser()', 'getAdminDashboardControllercreateUserService', true],
            'App\\Controller\\AdminDashboardController:listUsers' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\AdminDashboardController::listUsers()', 'getAdminDashboardControllerlistUsersService', true],
            'App\\Controller\\AdminDashboardController:updateUser' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\AdminDashboardController::updateUser()', 'getAdminDashboardControllerupdateUserService', true],
            'App\\Controller\\AdminDashboardController:deleteUser' => ['privates', '.service_locator.bTA9FKH.App\\Controller\\AdminDashboardController::deleteUser()', 'getAdminDashboardControllerdeleteUserService', true],
            'App\\Controller\\AvisController:createAvis' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\AvisController::createAvis()', 'getAvisControllercreateAvisService', true],
            'App\\Controller\\AvisController:getValidatedAvis' => ['privates', '.service_locator.0qdY07o.App\\Controller\\AvisController::getValidatedAvis()', 'getAvisControllergetValidatedAvisService', true],
            'App\\Controller\\AvisController:getPendingAvis' => ['privates', '.service_locator.0qdY07o.App\\Controller\\AvisController::getPendingAvis()', 'getAvisControllergetPendingAvisService', true],
            'App\\Controller\\AvisController:validateAvis' => ['privates', '.service_locator.4BBdIOf.App\\Controller\\AvisController::validateAvis()', 'getAvisControllervalidateAvisService', true],
            'App\\Controller\\AvisController:deleteAvis' => ['privates', '.service_locator.4BBdIOf.App\\Controller\\AvisController::deleteAvis()', 'getAvisControllerdeleteAvisService', true],
            'App\\Controller\\ConsultationController:incrementConsultation' => ['privates', '.service_locator.F1jaNar.App\\Controller\\ConsultationController::incrementConsultation()', 'getConsultationControllerincrementConsultationService', true],
            'App\\Controller\\ConsultationController:getConsultations' => ['privates', '.service_locator..sUqPH6.App\\Controller\\ConsultationController::getConsultations()', 'getConsultationControllergetConsultationsService', true],
            'App\\Controller\\ContactController:deleteContactRequest' => ['privates', '.service_locator.qIOAC1G.App\\Controller\\ContactController::deleteContactRequest()', 'getContactControllerdeleteContactRequestService', true],
            'App\\Controller\\ContactController:testEmail' => ['privates', '.service_locator.emggfWL.App\\Controller\\ContactController::testEmail()', 'getContactControllertestEmailService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminDashboardController::createUser' => '?',
            'App\\Controller\\AdminDashboardController::listUsers' => '?',
            'App\\Controller\\AdminDashboardController::updateUser' => '?',
            'App\\Controller\\AdminDashboardController::deleteUser' => '?',
            'App\\Controller\\AvisController::createAvis' => '?',
            'App\\Controller\\AvisController::getValidatedAvis' => '?',
            'App\\Controller\\AvisController::getPendingAvis' => '?',
            'App\\Controller\\AvisController::validateAvis' => '?',
            'App\\Controller\\AvisController::deleteAvis' => '?',
            'App\\Controller\\ConsultationController::incrementConsultation' => '?',
            'App\\Controller\\ConsultationController::getConsultations' => '?',
            'App\\Controller\\ContactController::deleteContactRequest' => '?',
            'App\\Controller\\ContactController::testEmail' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminDashboardController:createUser' => '?',
            'App\\Controller\\AdminDashboardController:listUsers' => '?',
            'App\\Controller\\AdminDashboardController:updateUser' => '?',
            'App\\Controller\\AdminDashboardController:deleteUser' => '?',
            'App\\Controller\\AvisController:createAvis' => '?',
            'App\\Controller\\AvisController:getValidatedAvis' => '?',
            'App\\Controller\\AvisController:getPendingAvis' => '?',
            'App\\Controller\\AvisController:validateAvis' => '?',
            'App\\Controller\\AvisController:deleteAvis' => '?',
            'App\\Controller\\ConsultationController:incrementConsultation' => '?',
            'App\\Controller\\ConsultationController:getConsultations' => '?',
            'App\\Controller\\ContactController:deleteContactRequest' => '?',
            'App\\Controller\\ContactController:testEmail' => '?',
        ]);
    }
}
