<?php

namespace ContainerDdEbTms;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvisControllergetValidatedAvisService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0qdY07o.App\Controller\AvisController::getValidatedAvis()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0qdY07o.App\\Controller\\AvisController::getValidatedAvis()'] = ($container->privates['.service_locator.0qdY07o'] ?? $container->load('get_ServiceLocator_0qdY07oService'))->withContext('App\\Controller\\AvisController::getValidatedAvis()', $container);
    }
}
