<?php

namespace ContainerDdEbTms;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllerdeleteContactRequestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qIOAC1G.App\Controller\ContactController::deleteContactRequest()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qIOAC1G.App\\Controller\\ContactController::deleteContactRequest()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['services', 'App\\Repository\\ContactRequestRepository', 'getContactRequestRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'repo' => 'App\\Repository\\ContactRequestRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\ContactController::deleteContactRequest()', $container);
    }
}
