<?php

namespace ContainerDdEbTms;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsultationControllergetConsultationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..sUqPH6.App\Controller\ConsultationController::getConsultations()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..sUqPH6.App\\Controller\\ConsultationController::getConsultations()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dm' => ['services', 'doctrine_mongodb.odm.default_document_manager', 'getDoctrineMongodb_Odm_DefaultDocumentManagerService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'dm' => '?',
            'em' => '?',
        ]))->withContext('App\\Controller\\ConsultationController::getConsultations()', $container);
    }
}
