<?php

namespace ContainerDdEbTms;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getYourDocumentClassService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Document\YourDocumentClass' shared autowired service.
     *
     * @return \App\Document\YourDocumentClass
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Document'.\DIRECTORY_SEPARATOR.'YourDocumentClass.php';

        return $container->services['App\\Document\\YourDocumentClass'] = new \App\Document\YourDocumentClass();
    }
}
