<?php

namespace MongoDBODMProxies\__CG__\App\Document;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Consultation extends \App\Document\Consultation implements \Doctrine\ODM\MongoDB\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'animalName' => [parent::class, 'animalName', null],
        "\0".parent::class."\0".'consultations' => [parent::class, 'consultations', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'animalName' => [parent::class, 'animalName', null],
        'consultations' => [parent::class, 'consultations', null],
        'id' => [parent::class, 'id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
