<?php

namespace ContainerC22kx7s;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FbS0cpjService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.fbS0cpj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fbS0cpj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailerService' => ['privates', '.errored.TV_5Q6A', NULL, 'Cannot determine controller argument for "App\\Controller\\ContactController::replyContactRequest()": the $mailerService argument is type-hinted with the non-existent class or interface: "App\\Controller\\MailerService". Did you forget to add a use statement?'],
        ], [
            'mailerService' => '?',
        ]);
    }
}
