<?php

namespace ContainerC22kx7s;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailerTestCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\MailerTestCommand' shared autowired service.
     *
     * @return \App\Command\MailerTestCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'MailerTestCommand.php';

        $container->privates['App\\Command\\MailerTestCommand'] = $instance = new \App\Command\MailerTestCommand(($container->privates['App\\Service\\MailerService'] ?? $container->load('getMailerServiceService')));

        $instance->setName('mailer:test');
        $instance->setDescription('Test de l\'envoi d\'un email');

        return $instance;
    }
}
