<?php

namespace ContainerC22kx7s;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNelmioApiDoc_RouteArgumentDescriber_MapQueryParameterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'nelmio_api_doc.route_argument_describer.map_query_parameter' shared service.
     *
     * @return \Nelmio\ApiDocBundle\RouteDescriber\RouteArgumentDescriber\SymfonyMapQueryParameterDescriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nelmio'.\DIRECTORY_SEPARATOR.'api-doc-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'RouteDescriber'.\DIRECTORY_SEPARATOR.'RouteArgumentDescriber'.\DIRECTORY_SEPARATOR.'RouteArgumentDescriberInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'zircote'.\DIRECTORY_SEPARATOR.'swagger-php'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Processors'.\DIRECTORY_SEPARATOR.'Concerns'.\DIRECTORY_SEPARATOR.'TypesTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nelmio'.\DIRECTORY_SEPARATOR.'api-doc-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'RouteDescriber'.\DIRECTORY_SEPARATOR.'RouteArgumentDescriber'.\DIRECTORY_SEPARATOR.'SymfonyMapQueryParameterDescriber.php';

        return $container->privates['nelmio_api_doc.route_argument_describer.map_query_parameter'] = new \Nelmio\ApiDocBundle\RouteDescriber\RouteArgumentDescriber\SymfonyMapQueryParameterDescriber();
    }
}
