<?php

namespace ContainerC22kx7s;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestMongoCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\TestMongoCommand' shared autowired service.
     *
     * @return \App\Command\TestMongoCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'TestMongoCommand.php';

        $container->privates['App\\Command\\TestMongoCommand'] = $instance = new \App\Command\TestMongoCommand();

        $instance->setName('app:test-mongo');
        $instance->setDescription('Test de la connexion à MongoDB et insertion d’un document.');

        return $instance;
    }
}
