"https://{default}/":
    type: upstream
    upstream: "frontend:http"

"https://{default}/api/":
    type: upstream
    upstream: "backend:http"

"http://{all}/":
    type: redirect
    to: "https://{all}/"
