<?php

namespace ContainerXvxb5EP;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllertestEmailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.emggfWL.App\Controller\ContactController::testEmail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.emggfWL.App\\Controller\\ContactController::testEmail()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailer' => ['services', 'App\\Service\\MailerService', 'getMailerServiceService', true],
        ], [
            'mailer' => 'App\\Service\\MailerService',
        ]))->withContext('App\\Controller\\ContactController::testEmail()', $container);
    }
}
