<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGyWsBeL\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGyWsBeL/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerGyWsBeL.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerGyWsBeL\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerGyWsBeL\App_KernelTestDebugContainer([
    'container.build_hash' => 'GyWsBeL',
    'container.build_id' => '72542b9e',
    'container.build_time' => 1740168739,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGyWsBeL');
